{{ config
(
    materialized = 'table'
)
}}

WITH CALLED_CONTRACTS AS (
SELECT 
rt.TO_ADDRESS AS ADDRESS,
MIN(rt.BLOCK_TIMESTAMP) AS FIRST_CALL_TIME
FROM SCROLL.RAW.TRACES rt
INNER JOIN SCROLL.RAW.CONTRACTS rc 
    ON rt.TO_ADDRESS = rc.ADDRESS
    AND rt.BLOCK_TIMESTAMP > rc.BLOCK_TIMESTAMP
    AND rt.TRACE_TYPE = 'call'
    AND rt.ERROR IS NULL
GROUP BY 1
)


SELECT 
src.ADDRESS,
src.BLOCK_TIMESTAMP AS CREATED_AT,
src.DEPLOYER,
CASE WHEN erc20.ADDRESS is not NULL THEN 'erc20'
    WHEN erc1155.ADDRESS is not NULL THEN 'erc1155'
    WHEN erc721.ADDRESS is not NULL THEN 'erc721'
    ELSE 'none'
    END AS TOKEN_TYPE,
CASE WHEN LENGTH(SUBSTR(BYTECODE, 3)) / 2 > 1000 
    THEN 1 ELSE 0 
    END AS IS_MIN_LENGTH,
CASE WHEN cc.ADDRESS IS NOT NULL 
    THEN 1 ELSE 0 
    END AS IS_USED
FROM SCROLL.RAW.CONTRACTS src
LEFT JOIN CALLED_CONTRACTS cc
    ON src.ADDRESS = cc.ADDRESS
LEFT JOIN SCROLL.RAW.ERC20_TOKENS erc20
    ON src.ADDRESS = erc20.ADDRESS 
LEFT JOIN SCROLL.RAW.ERC1155_TOKENS erc1155
    ON src.ADDRESS = erc1155.ADDRESS 
LEFT JOIN SCROLL.RAW.ERC721_TOKENS erc721
    ON src.ADDRESS = erc721.ADDRESS 